# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GpsData.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='GpsData.proto',
  package='akproto1',
  syntax='proto3',
  serialized_pb=_b('\n\rGpsData.proto\x12\x08\x61kproto1\"\x82\x01\n\x07GpsData\x12\x10\n\x08latitude\x18\x01 \x01(\x11\x12\x11\n\tlongitude\x18\x02 \x01(\x11\x12\x10\n\x08\x61ltitude\x18\x03 \x01(\x11\x12\x0c\n\x04hdop\x18\x04 \x01(\r\x12\x1c\n\x14number_of_satellites\x18\x05 \x01(\r\x12\x14\n\x0cis_valid_fix\x18\x06 \x01(\x08\x62\x06proto3')
)




_GPSDATA = _descriptor.Descriptor(
  name='GpsData',
  full_name='akproto1.GpsData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='latitude', full_name='akproto1.GpsData.latitude', index=0,
      number=1, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='akproto1.GpsData.longitude', index=1,
      number=2, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='altitude', full_name='akproto1.GpsData.altitude', index=2,
      number=3, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hdop', full_name='akproto1.GpsData.hdop', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='number_of_satellites', full_name='akproto1.GpsData.number_of_satellites', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='is_valid_fix', full_name='akproto1.GpsData.is_valid_fix', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=158,
)

DESCRIPTOR.message_types_by_name['GpsData'] = _GPSDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GpsData = _reflection.GeneratedProtocolMessageType('GpsData', (_message.Message,), dict(
  DESCRIPTOR = _GPSDATA,
  __module__ = 'GpsData_pb2'
  # @@protoc_insertion_point(class_scope:akproto1.GpsData)
  ))
_sym_db.RegisterMessage(GpsData)


# @@protoc_insertion_point(module_scope)
