# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LPWANServerMessage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='LPWANServerMessage.proto',
  package='akproto1',
  syntax='proto3',
  serialized_pb=_b('\n\x18LPWANServerMessage.proto\x12\x08\x61kproto1\"\x13\n\x11GetSettingCommand\"\x13\n\x11SetSettingCommand\"!\n\rRebootCommand\x12\x10\n\x08\x64\x65lay_ms\x18\x01 \x01(\x04\"-\n\x19\x45nterHibernateModeCommand\x12\x10\n\x08\x64\x65lay_ms\x18\x01 \x01(\x04\"\x14\n\x12TransmitNowCommand\"\xc5\x02\n\x12LPWANServerCommand\x12\x16\n\x0e\x63ommand_number\x18\x01 \x01(\x04\x12\x34\n\x0ctransmit_now\x18\x02 \x01(\x0b\x32\x1c.akproto1.TransmitNowCommandH\x00\x12\x32\n\x0bget_setting\x18\x03 \x01(\x0b\x32\x1b.akproto1.GetSettingCommandH\x00\x12\x32\n\x0bset_setting\x18\x04 \x01(\x0b\x32\x1b.akproto1.SetSettingCommandH\x00\x12)\n\x06reboot\x18\x05 \x01(\x0b\x32\x17.akproto1.RebootCommandH\x00\x12\x43\n\x14\x65nter_hibernate_mode\x18\x06 \x01(\x0b\x32#.akproto1.EnterHibernateModeCommandH\x00\x42\t\n\x07\x63ommand\"d\n\x12LPWANServerMessage\x12\x18\n\x10protocol_version\x18\x01 \x01(\x04\x12\x34\n\x0eserver_command\x18\x02 \x03(\x0b\x32\x1c.akproto1.LPWANServerCommandb\x06proto3')
)




_GETSETTINGCOMMAND = _descriptor.Descriptor(
  name='GetSettingCommand',
  full_name='akproto1.GetSettingCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=57,
)


_SETSETTINGCOMMAND = _descriptor.Descriptor(
  name='SetSettingCommand',
  full_name='akproto1.SetSettingCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=78,
)


_REBOOTCOMMAND = _descriptor.Descriptor(
  name='RebootCommand',
  full_name='akproto1.RebootCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='delay_ms', full_name='akproto1.RebootCommand.delay_ms', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=113,
)


_ENTERHIBERNATEMODECOMMAND = _descriptor.Descriptor(
  name='EnterHibernateModeCommand',
  full_name='akproto1.EnterHibernateModeCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='delay_ms', full_name='akproto1.EnterHibernateModeCommand.delay_ms', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=115,
  serialized_end=160,
)


_TRANSMITNOWCOMMAND = _descriptor.Descriptor(
  name='TransmitNowCommand',
  full_name='akproto1.TransmitNowCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=162,
  serialized_end=182,
)


_LPWANSERVERCOMMAND = _descriptor.Descriptor(
  name='LPWANServerCommand',
  full_name='akproto1.LPWANServerCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='command_number', full_name='akproto1.LPWANServerCommand.command_number', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='transmit_now', full_name='akproto1.LPWANServerCommand.transmit_now', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='get_setting', full_name='akproto1.LPWANServerCommand.get_setting', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='set_setting', full_name='akproto1.LPWANServerCommand.set_setting', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reboot', full_name='akproto1.LPWANServerCommand.reboot', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='enter_hibernate_mode', full_name='akproto1.LPWANServerCommand.enter_hibernate_mode', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='command', full_name='akproto1.LPWANServerCommand.command',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=185,
  serialized_end=510,
)


_LPWANSERVERMESSAGE = _descriptor.Descriptor(
  name='LPWANServerMessage',
  full_name='akproto1.LPWANServerMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='protocol_version', full_name='akproto1.LPWANServerMessage.protocol_version', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='server_command', full_name='akproto1.LPWANServerMessage.server_command', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=512,
  serialized_end=612,
)

_LPWANSERVERCOMMAND.fields_by_name['transmit_now'].message_type = _TRANSMITNOWCOMMAND
_LPWANSERVERCOMMAND.fields_by_name['get_setting'].message_type = _GETSETTINGCOMMAND
_LPWANSERVERCOMMAND.fields_by_name['set_setting'].message_type = _SETSETTINGCOMMAND
_LPWANSERVERCOMMAND.fields_by_name['reboot'].message_type = _REBOOTCOMMAND
_LPWANSERVERCOMMAND.fields_by_name['enter_hibernate_mode'].message_type = _ENTERHIBERNATEMODECOMMAND
_LPWANSERVERCOMMAND.oneofs_by_name['command'].fields.append(
  _LPWANSERVERCOMMAND.fields_by_name['transmit_now'])
_LPWANSERVERCOMMAND.fields_by_name['transmit_now'].containing_oneof = _LPWANSERVERCOMMAND.oneofs_by_name['command']
_LPWANSERVERCOMMAND.oneofs_by_name['command'].fields.append(
  _LPWANSERVERCOMMAND.fields_by_name['get_setting'])
_LPWANSERVERCOMMAND.fields_by_name['get_setting'].containing_oneof = _LPWANSERVERCOMMAND.oneofs_by_name['command']
_LPWANSERVERCOMMAND.oneofs_by_name['command'].fields.append(
  _LPWANSERVERCOMMAND.fields_by_name['set_setting'])
_LPWANSERVERCOMMAND.fields_by_name['set_setting'].containing_oneof = _LPWANSERVERCOMMAND.oneofs_by_name['command']
_LPWANSERVERCOMMAND.oneofs_by_name['command'].fields.append(
  _LPWANSERVERCOMMAND.fields_by_name['reboot'])
_LPWANSERVERCOMMAND.fields_by_name['reboot'].containing_oneof = _LPWANSERVERCOMMAND.oneofs_by_name['command']
_LPWANSERVERCOMMAND.oneofs_by_name['command'].fields.append(
  _LPWANSERVERCOMMAND.fields_by_name['enter_hibernate_mode'])
_LPWANSERVERCOMMAND.fields_by_name['enter_hibernate_mode'].containing_oneof = _LPWANSERVERCOMMAND.oneofs_by_name['command']
_LPWANSERVERMESSAGE.fields_by_name['server_command'].message_type = _LPWANSERVERCOMMAND
DESCRIPTOR.message_types_by_name['GetSettingCommand'] = _GETSETTINGCOMMAND
DESCRIPTOR.message_types_by_name['SetSettingCommand'] = _SETSETTINGCOMMAND
DESCRIPTOR.message_types_by_name['RebootCommand'] = _REBOOTCOMMAND
DESCRIPTOR.message_types_by_name['EnterHibernateModeCommand'] = _ENTERHIBERNATEMODECOMMAND
DESCRIPTOR.message_types_by_name['TransmitNowCommand'] = _TRANSMITNOWCOMMAND
DESCRIPTOR.message_types_by_name['LPWANServerCommand'] = _LPWANSERVERCOMMAND
DESCRIPTOR.message_types_by_name['LPWANServerMessage'] = _LPWANSERVERMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetSettingCommand = _reflection.GeneratedProtocolMessageType('GetSettingCommand', (_message.Message,), dict(
  DESCRIPTOR = _GETSETTINGCOMMAND,
  __module__ = 'LPWANServerMessage_pb2'
  # @@protoc_insertion_point(class_scope:akproto1.GetSettingCommand)
  ))
_sym_db.RegisterMessage(GetSettingCommand)

SetSettingCommand = _reflection.GeneratedProtocolMessageType('SetSettingCommand', (_message.Message,), dict(
  DESCRIPTOR = _SETSETTINGCOMMAND,
  __module__ = 'LPWANServerMessage_pb2'
  # @@protoc_insertion_point(class_scope:akproto1.SetSettingCommand)
  ))
_sym_db.RegisterMessage(SetSettingCommand)

RebootCommand = _reflection.GeneratedProtocolMessageType('RebootCommand', (_message.Message,), dict(
  DESCRIPTOR = _REBOOTCOMMAND,
  __module__ = 'LPWANServerMessage_pb2'
  # @@protoc_insertion_point(class_scope:akproto1.RebootCommand)
  ))
_sym_db.RegisterMessage(RebootCommand)

EnterHibernateModeCommand = _reflection.GeneratedProtocolMessageType('EnterHibernateModeCommand', (_message.Message,), dict(
  DESCRIPTOR = _ENTERHIBERNATEMODECOMMAND,
  __module__ = 'LPWANServerMessage_pb2'
  # @@protoc_insertion_point(class_scope:akproto1.EnterHibernateModeCommand)
  ))
_sym_db.RegisterMessage(EnterHibernateModeCommand)

TransmitNowCommand = _reflection.GeneratedProtocolMessageType('TransmitNowCommand', (_message.Message,), dict(
  DESCRIPTOR = _TRANSMITNOWCOMMAND,
  __module__ = 'LPWANServerMessage_pb2'
  # @@protoc_insertion_point(class_scope:akproto1.TransmitNowCommand)
  ))
_sym_db.RegisterMessage(TransmitNowCommand)

LPWANServerCommand = _reflection.GeneratedProtocolMessageType('LPWANServerCommand', (_message.Message,), dict(
  DESCRIPTOR = _LPWANSERVERCOMMAND,
  __module__ = 'LPWANServerMessage_pb2'
  # @@protoc_insertion_point(class_scope:akproto1.LPWANServerCommand)
  ))
_sym_db.RegisterMessage(LPWANServerCommand)

LPWANServerMessage = _reflection.GeneratedProtocolMessageType('LPWANServerMessage', (_message.Message,), dict(
  DESCRIPTOR = _LPWANSERVERMESSAGE,
  __module__ = 'LPWANServerMessage_pb2'
  # @@protoc_insertion_point(class_scope:akproto1.LPWANServerMessage)
  ))
_sym_db.RegisterMessage(LPWANServerMessage)


# @@protoc_insertion_point(module_scope)
