# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LPWANServerMessage_new.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='LPWANServerMessage_new.proto',
  package='lpwan1',
  syntax='proto3',
  serialized_pb=_b('\n\x1cLPWANServerMessage_new.proto\x12\x06lpwan1\"\x13\n\x11GetSettingCommand\"\x13\n\x11SetSettingCommand\"!\n\rRebootCommand\x12\x10\n\x08\x64\x65lay_ms\x18\x01 \x01(\x04\"-\n\x19\x45nterHibernateModeCommand\x12\x10\n\x08\x64\x65lay_ms\x18\x01 \x01(\x04\"\x14\n\x12TransmitNowCommand\"e\n\x1eSetCellularActivityModeCommand\x12\x43\n\x16\x63\x65llular_activity_mode\x18\x01 \x01(\x0e\x32#.lpwan1.CellularActivityModeCommand\"\x89\x03\n\x12LPWANServerCommand\x12\x16\n\x0e\x63ommand_number\x18\x01 \x01(\x04\x12\x32\n\x0ctransmit_now\x18\x02 \x01(\x0b\x32\x1a.lpwan1.TransmitNowCommandH\x00\x12\x30\n\x0bget_setting\x18\x03 \x01(\x0b\x32\x19.lpwan1.GetSettingCommandH\x00\x12\x30\n\x0bset_setting\x18\x04 \x01(\x0b\x32\x19.lpwan1.SetSettingCommandH\x00\x12\'\n\x06reboot\x18\x05 \x01(\x0b\x32\x15.lpwan1.RebootCommandH\x00\x12\x41\n\x14\x65nter_hibernate_mode\x18\x06 \x01(\x0b\x32!.lpwan1.EnterHibernateModeCommandH\x00\x12L\n\x1aset_cellular_activity_mode\x18\x07 \x01(\x0b\x32&.lpwan1.SetCellularActivityModeCommandH\x00\x42\t\n\x07\x63ommand\"b\n\x12LPWANServerMessage\x12\x18\n\x10protocol_version\x18\x01 \x01(\x04\x12\x32\n\x0eserver_command\x18\x02 \x03(\x0b\x32\x1a.lpwan1.LPWANServerCommand*;\n\x1b\x43\x65llularActivityModeCommand\x12\x06\n\x02ON\x10\x00\x12\x07\n\x03OFF\x10\x01\x12\x0b\n\x07ON_HOLD\x10\x02\x62\x06proto3')
)

_CELLULARACTIVITYMODECOMMAND = _descriptor.EnumDescriptor(
  name='CellularActivityModeCommand',
  full_name='lpwan1.CellularActivityModeCommand',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ON', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OFF', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ON_HOLD', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=785,
  serialized_end=844,
)
_sym_db.RegisterEnumDescriptor(_CELLULARACTIVITYMODECOMMAND)

CellularActivityModeCommand = enum_type_wrapper.EnumTypeWrapper(_CELLULARACTIVITYMODECOMMAND)
ON = 0
OFF = 1
ON_HOLD = 2



_GETSETTINGCOMMAND = _descriptor.Descriptor(
  name='GetSettingCommand',
  full_name='lpwan1.GetSettingCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=59,
)


_SETSETTINGCOMMAND = _descriptor.Descriptor(
  name='SetSettingCommand',
  full_name='lpwan1.SetSettingCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=80,
)


_REBOOTCOMMAND = _descriptor.Descriptor(
  name='RebootCommand',
  full_name='lpwan1.RebootCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='delay_ms', full_name='lpwan1.RebootCommand.delay_ms', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=115,
)


_ENTERHIBERNATEMODECOMMAND = _descriptor.Descriptor(
  name='EnterHibernateModeCommand',
  full_name='lpwan1.EnterHibernateModeCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='delay_ms', full_name='lpwan1.EnterHibernateModeCommand.delay_ms', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=162,
)


_TRANSMITNOWCOMMAND = _descriptor.Descriptor(
  name='TransmitNowCommand',
  full_name='lpwan1.TransmitNowCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=164,
  serialized_end=184,
)


_SETCELLULARACTIVITYMODECOMMAND = _descriptor.Descriptor(
  name='SetCellularActivityModeCommand',
  full_name='lpwan1.SetCellularActivityModeCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cellular_activity_mode', full_name='lpwan1.SetCellularActivityModeCommand.cellular_activity_mode', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=186,
  serialized_end=287,
)


_LPWANSERVERCOMMAND = _descriptor.Descriptor(
  name='LPWANServerCommand',
  full_name='lpwan1.LPWANServerCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='command_number', full_name='lpwan1.LPWANServerCommand.command_number', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='transmit_now', full_name='lpwan1.LPWANServerCommand.transmit_now', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='get_setting', full_name='lpwan1.LPWANServerCommand.get_setting', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='set_setting', full_name='lpwan1.LPWANServerCommand.set_setting', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reboot', full_name='lpwan1.LPWANServerCommand.reboot', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='enter_hibernate_mode', full_name='lpwan1.LPWANServerCommand.enter_hibernate_mode', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='set_cellular_activity_mode', full_name='lpwan1.LPWANServerCommand.set_cellular_activity_mode', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='command', full_name='lpwan1.LPWANServerCommand.command',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=290,
  serialized_end=683,
)


_LPWANSERVERMESSAGE = _descriptor.Descriptor(
  name='LPWANServerMessage',
  full_name='lpwan1.LPWANServerMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='protocol_version', full_name='lpwan1.LPWANServerMessage.protocol_version', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='server_command', full_name='lpwan1.LPWANServerMessage.server_command', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=685,
  serialized_end=783,
)

_SETCELLULARACTIVITYMODECOMMAND.fields_by_name['cellular_activity_mode'].enum_type = _CELLULARACTIVITYMODECOMMAND
_LPWANSERVERCOMMAND.fields_by_name['transmit_now'].message_type = _TRANSMITNOWCOMMAND
_LPWANSERVERCOMMAND.fields_by_name['get_setting'].message_type = _GETSETTINGCOMMAND
_LPWANSERVERCOMMAND.fields_by_name['set_setting'].message_type = _SETSETTINGCOMMAND
_LPWANSERVERCOMMAND.fields_by_name['reboot'].message_type = _REBOOTCOMMAND
_LPWANSERVERCOMMAND.fields_by_name['enter_hibernate_mode'].message_type = _ENTERHIBERNATEMODECOMMAND
_LPWANSERVERCOMMAND.fields_by_name['set_cellular_activity_mode'].message_type = _SETCELLULARACTIVITYMODECOMMAND
_LPWANSERVERCOMMAND.oneofs_by_name['command'].fields.append(
  _LPWANSERVERCOMMAND.fields_by_name['transmit_now'])
_LPWANSERVERCOMMAND.fields_by_name['transmit_now'].containing_oneof = _LPWANSERVERCOMMAND.oneofs_by_name['command']
_LPWANSERVERCOMMAND.oneofs_by_name['command'].fields.append(
  _LPWANSERVERCOMMAND.fields_by_name['get_setting'])
_LPWANSERVERCOMMAND.fields_by_name['get_setting'].containing_oneof = _LPWANSERVERCOMMAND.oneofs_by_name['command']
_LPWANSERVERCOMMAND.oneofs_by_name['command'].fields.append(
  _LPWANSERVERCOMMAND.fields_by_name['set_setting'])
_LPWANSERVERCOMMAND.fields_by_name['set_setting'].containing_oneof = _LPWANSERVERCOMMAND.oneofs_by_name['command']
_LPWANSERVERCOMMAND.oneofs_by_name['command'].fields.append(
  _LPWANSERVERCOMMAND.fields_by_name['reboot'])
_LPWANSERVERCOMMAND.fields_by_name['reboot'].containing_oneof = _LPWANSERVERCOMMAND.oneofs_by_name['command']
_LPWANSERVERCOMMAND.oneofs_by_name['command'].fields.append(
  _LPWANSERVERCOMMAND.fields_by_name['enter_hibernate_mode'])
_LPWANSERVERCOMMAND.fields_by_name['enter_hibernate_mode'].containing_oneof = _LPWANSERVERCOMMAND.oneofs_by_name['command']
_LPWANSERVERCOMMAND.oneofs_by_name['command'].fields.append(
  _LPWANSERVERCOMMAND.fields_by_name['set_cellular_activity_mode'])
_LPWANSERVERCOMMAND.fields_by_name['set_cellular_activity_mode'].containing_oneof = _LPWANSERVERCOMMAND.oneofs_by_name['command']
_LPWANSERVERMESSAGE.fields_by_name['server_command'].message_type = _LPWANSERVERCOMMAND
DESCRIPTOR.message_types_by_name['GetSettingCommand'] = _GETSETTINGCOMMAND
DESCRIPTOR.message_types_by_name['SetSettingCommand'] = _SETSETTINGCOMMAND
DESCRIPTOR.message_types_by_name['RebootCommand'] = _REBOOTCOMMAND
DESCRIPTOR.message_types_by_name['EnterHibernateModeCommand'] = _ENTERHIBERNATEMODECOMMAND
DESCRIPTOR.message_types_by_name['TransmitNowCommand'] = _TRANSMITNOWCOMMAND
DESCRIPTOR.message_types_by_name['SetCellularActivityModeCommand'] = _SETCELLULARACTIVITYMODECOMMAND
DESCRIPTOR.message_types_by_name['LPWANServerCommand'] = _LPWANSERVERCOMMAND
DESCRIPTOR.message_types_by_name['LPWANServerMessage'] = _LPWANSERVERMESSAGE
DESCRIPTOR.enum_types_by_name['CellularActivityModeCommand'] = _CELLULARACTIVITYMODECOMMAND
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetSettingCommand = _reflection.GeneratedProtocolMessageType('GetSettingCommand', (_message.Message,), dict(
  DESCRIPTOR = _GETSETTINGCOMMAND,
  __module__ = 'LPWANServerMessage_new_pb2'
  # @@protoc_insertion_point(class_scope:lpwan1.GetSettingCommand)
  ))
_sym_db.RegisterMessage(GetSettingCommand)

SetSettingCommand = _reflection.GeneratedProtocolMessageType('SetSettingCommand', (_message.Message,), dict(
  DESCRIPTOR = _SETSETTINGCOMMAND,
  __module__ = 'LPWANServerMessage_new_pb2'
  # @@protoc_insertion_point(class_scope:lpwan1.SetSettingCommand)
  ))
_sym_db.RegisterMessage(SetSettingCommand)

RebootCommand = _reflection.GeneratedProtocolMessageType('RebootCommand', (_message.Message,), dict(
  DESCRIPTOR = _REBOOTCOMMAND,
  __module__ = 'LPWANServerMessage_new_pb2'
  # @@protoc_insertion_point(class_scope:lpwan1.RebootCommand)
  ))
_sym_db.RegisterMessage(RebootCommand)

EnterHibernateModeCommand = _reflection.GeneratedProtocolMessageType('EnterHibernateModeCommand', (_message.Message,), dict(
  DESCRIPTOR = _ENTERHIBERNATEMODECOMMAND,
  __module__ = 'LPWANServerMessage_new_pb2'
  # @@protoc_insertion_point(class_scope:lpwan1.EnterHibernateModeCommand)
  ))
_sym_db.RegisterMessage(EnterHibernateModeCommand)

TransmitNowCommand = _reflection.GeneratedProtocolMessageType('TransmitNowCommand', (_message.Message,), dict(
  DESCRIPTOR = _TRANSMITNOWCOMMAND,
  __module__ = 'LPWANServerMessage_new_pb2'
  # @@protoc_insertion_point(class_scope:lpwan1.TransmitNowCommand)
  ))
_sym_db.RegisterMessage(TransmitNowCommand)

SetCellularActivityModeCommand = _reflection.GeneratedProtocolMessageType('SetCellularActivityModeCommand', (_message.Message,), dict(
  DESCRIPTOR = _SETCELLULARACTIVITYMODECOMMAND,
  __module__ = 'LPWANServerMessage_new_pb2'
  # @@protoc_insertion_point(class_scope:lpwan1.SetCellularActivityModeCommand)
  ))
_sym_db.RegisterMessage(SetCellularActivityModeCommand)

LPWANServerCommand = _reflection.GeneratedProtocolMessageType('LPWANServerCommand', (_message.Message,), dict(
  DESCRIPTOR = _LPWANSERVERCOMMAND,
  __module__ = 'LPWANServerMessage_new_pb2'
  # @@protoc_insertion_point(class_scope:lpwan1.LPWANServerCommand)
  ))
_sym_db.RegisterMessage(LPWANServerCommand)

LPWANServerMessage = _reflection.GeneratedProtocolMessageType('LPWANServerMessage', (_message.Message,), dict(
  DESCRIPTOR = _LPWANSERVERMESSAGE,
  __module__ = 'LPWANServerMessage_new_pb2'
  # @@protoc_insertion_point(class_scope:lpwan1.LPWANServerMessage)
  ))
_sym_db.RegisterMessage(LPWANServerMessage)


# @@protoc_insertion_point(module_scope)
