# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LPWANClientMessage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import proto.ChannelType_pb2 as ChannelType__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='LPWANClientMessage.proto',
  package='akproto1',
  syntax='proto3',
  serialized_pb=_b('\n\x18LPWANClientMessage.proto\x12\x08\x61kproto1\x1a\x11\x43hannelType.proto\"\xeb\x01\n\x13LPWANSamplesMessage\x12\x16\n\x0e\x63hannel_number\x18\x01 \x01(\r\x12+\n\x0c\x63hannel_type\x18\x02 \x01(\x0e\x32\x15.akproto1.ChannelType\x12\x11\n\ttimestamp\x18\x03 \x01(\x04\x12\x16\n\x0cuint64_value\x18\x04 \x01(\x04H\x00\x12\x16\n\x0csint64_value\x18\x05 \x01(\x12H\x00\x12\x15\n\x0b\x66loat_value\x18\x06 \x01(\x02H\x00\x12\x16\n\x0c\x64ouble_value\x18\x07 \x01(\x01H\x00\x12\x14\n\nbool_value\x18\x08 \x01(\x08H\x00\x42\x07\n\x05value\"f\n\x12LPWANClientMessage\x12\x18\n\x10protocol_version\x18\x01 \x01(\x04\x12\x36\n\x0fsample_messages\x18\x02 \x03(\x0b\x32\x1d.akproto1.LPWANSamplesMessageb\x06proto3')
  ,
  dependencies=[ChannelType__pb2.DESCRIPTOR,])




_LPWANSAMPLESMESSAGE = _descriptor.Descriptor(
  name='LPWANSamplesMessage',
  full_name='akproto1.LPWANSamplesMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='channel_number', full_name='akproto1.LPWANSamplesMessage.channel_number', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='channel_type', full_name='akproto1.LPWANSamplesMessage.channel_type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='akproto1.LPWANSamplesMessage.timestamp', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uint64_value', full_name='akproto1.LPWANSamplesMessage.uint64_value', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sint64_value', full_name='akproto1.LPWANSamplesMessage.sint64_value', index=4,
      number=5, type=18, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='float_value', full_name='akproto1.LPWANSamplesMessage.float_value', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='double_value', full_name='akproto1.LPWANSamplesMessage.double_value', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bool_value', full_name='akproto1.LPWANSamplesMessage.bool_value', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='value', full_name='akproto1.LPWANSamplesMessage.value',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=58,
  serialized_end=293,
)


_LPWANCLIENTMESSAGE = _descriptor.Descriptor(
  name='LPWANClientMessage',
  full_name='akproto1.LPWANClientMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='protocol_version', full_name='akproto1.LPWANClientMessage.protocol_version', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sample_messages', full_name='akproto1.LPWANClientMessage.sample_messages', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=295,
  serialized_end=397,
)

_LPWANSAMPLESMESSAGE.fields_by_name['channel_type'].enum_type = ChannelType__pb2._CHANNELTYPE
_LPWANSAMPLESMESSAGE.oneofs_by_name['value'].fields.append(
  _LPWANSAMPLESMESSAGE.fields_by_name['uint64_value'])
_LPWANSAMPLESMESSAGE.fields_by_name['uint64_value'].containing_oneof = _LPWANSAMPLESMESSAGE.oneofs_by_name['value']
_LPWANSAMPLESMESSAGE.oneofs_by_name['value'].fields.append(
  _LPWANSAMPLESMESSAGE.fields_by_name['sint64_value'])
_LPWANSAMPLESMESSAGE.fields_by_name['sint64_value'].containing_oneof = _LPWANSAMPLESMESSAGE.oneofs_by_name['value']
_LPWANSAMPLESMESSAGE.oneofs_by_name['value'].fields.append(
  _LPWANSAMPLESMESSAGE.fields_by_name['float_value'])
_LPWANSAMPLESMESSAGE.fields_by_name['float_value'].containing_oneof = _LPWANSAMPLESMESSAGE.oneofs_by_name['value']
_LPWANSAMPLESMESSAGE.oneofs_by_name['value'].fields.append(
  _LPWANSAMPLESMESSAGE.fields_by_name['double_value'])
_LPWANSAMPLESMESSAGE.fields_by_name['double_value'].containing_oneof = _LPWANSAMPLESMESSAGE.oneofs_by_name['value']
_LPWANSAMPLESMESSAGE.oneofs_by_name['value'].fields.append(
  _LPWANSAMPLESMESSAGE.fields_by_name['bool_value'])
_LPWANSAMPLESMESSAGE.fields_by_name['bool_value'].containing_oneof = _LPWANSAMPLESMESSAGE.oneofs_by_name['value']
_LPWANCLIENTMESSAGE.fields_by_name['sample_messages'].message_type = _LPWANSAMPLESMESSAGE
DESCRIPTOR.message_types_by_name['LPWANSamplesMessage'] = _LPWANSAMPLESMESSAGE
DESCRIPTOR.message_types_by_name['LPWANClientMessage'] = _LPWANCLIENTMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LPWANSamplesMessage = _reflection.GeneratedProtocolMessageType('LPWANSamplesMessage', (_message.Message,), dict(
  DESCRIPTOR = _LPWANSAMPLESMESSAGE,
  __module__ = 'LPWANClientMessage_pb2'
  # @@protoc_insertion_point(class_scope:akproto1.LPWANSamplesMessage)
  ))
_sym_db.RegisterMessage(LPWANSamplesMessage)

LPWANClientMessage = _reflection.GeneratedProtocolMessageType('LPWANClientMessage', (_message.Message,), dict(
  DESCRIPTOR = _LPWANCLIENTMESSAGE,
  __module__ = 'LPWANClientMessage_pb2'
  # @@protoc_insertion_point(class_scope:akproto1.LPWANClientMessage)
  ))
_sym_db.RegisterMessage(LPWANClientMessage)


# @@protoc_insertion_point(module_scope)
