# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PeriodicSamples.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import proto.Sample_pb2 as Sample__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='PeriodicSamples.proto',
  package='akproto1',
  syntax='proto3',
  serialized_pb=_b('\n\x15PeriodicSamples.proto\x12\x08\x61kproto1\x1a\x0cSample.proto\"`\n\x0fPeriodicSamples\x12\x17\n\x0f\x66irst_timestamp\x18\x01 \x01(\x04\x12\x10\n\x08interval\x18\x02 \x01(\x04\x12\"\n\x04\x64\x61ta\x18\x03 \x03(\x0b\x32\x14.akproto1.SampleDatab\x06proto3')
  ,
  dependencies=[Sample__pb2.DESCRIPTOR,])




_PERIODICSAMPLES = _descriptor.Descriptor(
  name='PeriodicSamples',
  full_name='akproto1.PeriodicSamples',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='first_timestamp', full_name='akproto1.PeriodicSamples.first_timestamp', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='interval', full_name='akproto1.PeriodicSamples.interval', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='akproto1.PeriodicSamples.data', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=145,
)

_PERIODICSAMPLES.fields_by_name['data'].message_type = Sample__pb2._SAMPLEDATA
DESCRIPTOR.message_types_by_name['PeriodicSamples'] = _PERIODICSAMPLES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PeriodicSamples = _reflection.GeneratedProtocolMessageType('PeriodicSamples', (_message.Message,), dict(
  DESCRIPTOR = _PERIODICSAMPLES,
  __module__ = 'PeriodicSamples_pb2'
  # @@protoc_insertion_point(class_scope:akproto1.PeriodicSamples)
  ))
_sym_db.RegisterMessage(PeriodicSamples)


# @@protoc_insertion_point(module_scope)
