# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ReportEndMessage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ReportEndMessage.proto',
  package='akproto1',
  syntax='proto3',
  serialized_pb=_b('\n\x16ReportEndMessage.proto\x12\x08\x61kproto1\"P\n\x10ReportEndMessage\x12\x11\n\treport_id\x18\x01 \x01(\x04\x12)\n\x06reason\x18\x02 \x01(\x0e\x32\x19.akproto1.ReportEndReason*-\n\x0fReportEndReason\x12\n\n\x06\x43LOSED\x10\x00\x12\x0e\n\nTERMINATED\x10\x01\x62\x06proto3')
)

_REPORTENDREASON = _descriptor.EnumDescriptor(
  name='ReportEndReason',
  full_name='akproto1.ReportEndReason',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CLOSED', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TERMINATED', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=118,
  serialized_end=163,
)
_sym_db.RegisterEnumDescriptor(_REPORTENDREASON)

ReportEndReason = enum_type_wrapper.EnumTypeWrapper(_REPORTENDREASON)
CLOSED = 0
TERMINATED = 1



_REPORTENDMESSAGE = _descriptor.Descriptor(
  name='ReportEndMessage',
  full_name='akproto1.ReportEndMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='report_id', full_name='akproto1.ReportEndMessage.report_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reason', full_name='akproto1.ReportEndMessage.reason', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=116,
)

_REPORTENDMESSAGE.fields_by_name['reason'].enum_type = _REPORTENDREASON
DESCRIPTOR.message_types_by_name['ReportEndMessage'] = _REPORTENDMESSAGE
DESCRIPTOR.enum_types_by_name['ReportEndReason'] = _REPORTENDREASON
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReportEndMessage = _reflection.GeneratedProtocolMessageType('ReportEndMessage', (_message.Message,), dict(
  DESCRIPTOR = _REPORTENDMESSAGE,
  __module__ = 'ReportEndMessage_pb2'
  # @@protoc_insertion_point(class_scope:akproto1.ReportEndMessage)
  ))
_sym_db.RegisterMessage(ReportEndMessage)


# @@protoc_insertion_point(module_scope)
