# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Sample.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import proto.GpsData_pb2 as GpsData__pb2
import proto.JPGData_pb2 as JPGData__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Sample.proto',
  package='akproto1',
  syntax='proto3',
  serialized_pb=_b('\n\x0cSample.proto\x12\x08\x61kproto1\x1a\rGpsData.proto\x1a\rJPGData.proto\"\xda\x01\n\nSampleData\x12\x16\n\x0cuint64_value\x18\x01 \x01(\x04H\x00\x12\x16\n\x0csint64_value\x18\x02 \x01(\x12H\x00\x12\x15\n\x0b\x66loat_value\x18\x03 \x01(\x02H\x00\x12\x16\n\x0c\x64ouble_value\x18\x04 \x01(\x01H\x00\x12\x14\n\nbool_value\x18\x05 \x01(\x08H\x00\x12&\n\tgps_value\x18\x06 \x01(\x0b\x32\x11.akproto1.GpsDataH\x00\x12&\n\tjpg_value\x18\x07 \x01(\x0b\x32\x11.akproto1.JPGDataH\x00\x42\x07\n\x05value\"]\n\rStampedSample\x12\x11\n\ttimestamp\x18\x01 \x01(\x04\x12\"\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x14.akproto1.SampleData\x12\x15\n\rreportChannel\x18\x03 \x01(\rb\x06proto3')
  ,
  dependencies=[GpsData__pb2.DESCRIPTOR,JPGData__pb2.DESCRIPTOR,])




_SAMPLEDATA = _descriptor.Descriptor(
  name='SampleData',
  full_name='akproto1.SampleData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uint64_value', full_name='akproto1.SampleData.uint64_value', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sint64_value', full_name='akproto1.SampleData.sint64_value', index=1,
      number=2, type=18, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='float_value', full_name='akproto1.SampleData.float_value', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='double_value', full_name='akproto1.SampleData.double_value', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bool_value', full_name='akproto1.SampleData.bool_value', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gps_value', full_name='akproto1.SampleData.gps_value', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='jpg_value', full_name='akproto1.SampleData.jpg_value', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='value', full_name='akproto1.SampleData.value',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=57,
  serialized_end=275,
)


_STAMPEDSAMPLE = _descriptor.Descriptor(
  name='StampedSample',
  full_name='akproto1.StampedSample',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='akproto1.StampedSample.timestamp', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='akproto1.StampedSample.data', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reportChannel', full_name='akproto1.StampedSample.reportChannel', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=277,
  serialized_end=370,
)

_SAMPLEDATA.fields_by_name['gps_value'].message_type = GpsData__pb2._GPSDATA
_SAMPLEDATA.fields_by_name['jpg_value'].message_type = JPGData__pb2._JPGDATA
_SAMPLEDATA.oneofs_by_name['value'].fields.append(
  _SAMPLEDATA.fields_by_name['uint64_value'])
_SAMPLEDATA.fields_by_name['uint64_value'].containing_oneof = _SAMPLEDATA.oneofs_by_name['value']
_SAMPLEDATA.oneofs_by_name['value'].fields.append(
  _SAMPLEDATA.fields_by_name['sint64_value'])
_SAMPLEDATA.fields_by_name['sint64_value'].containing_oneof = _SAMPLEDATA.oneofs_by_name['value']
_SAMPLEDATA.oneofs_by_name['value'].fields.append(
  _SAMPLEDATA.fields_by_name['float_value'])
_SAMPLEDATA.fields_by_name['float_value'].containing_oneof = _SAMPLEDATA.oneofs_by_name['value']
_SAMPLEDATA.oneofs_by_name['value'].fields.append(
  _SAMPLEDATA.fields_by_name['double_value'])
_SAMPLEDATA.fields_by_name['double_value'].containing_oneof = _SAMPLEDATA.oneofs_by_name['value']
_SAMPLEDATA.oneofs_by_name['value'].fields.append(
  _SAMPLEDATA.fields_by_name['bool_value'])
_SAMPLEDATA.fields_by_name['bool_value'].containing_oneof = _SAMPLEDATA.oneofs_by_name['value']
_SAMPLEDATA.oneofs_by_name['value'].fields.append(
  _SAMPLEDATA.fields_by_name['gps_value'])
_SAMPLEDATA.fields_by_name['gps_value'].containing_oneof = _SAMPLEDATA.oneofs_by_name['value']
_SAMPLEDATA.oneofs_by_name['value'].fields.append(
  _SAMPLEDATA.fields_by_name['jpg_value'])
_SAMPLEDATA.fields_by_name['jpg_value'].containing_oneof = _SAMPLEDATA.oneofs_by_name['value']
_STAMPEDSAMPLE.fields_by_name['data'].message_type = _SAMPLEDATA
DESCRIPTOR.message_types_by_name['SampleData'] = _SAMPLEDATA
DESCRIPTOR.message_types_by_name['StampedSample'] = _STAMPEDSAMPLE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SampleData = _reflection.GeneratedProtocolMessageType('SampleData', (_message.Message,), dict(
  DESCRIPTOR = _SAMPLEDATA,
  __module__ = 'Sample_pb2'
  # @@protoc_insertion_point(class_scope:akproto1.SampleData)
  ))
_sym_db.RegisterMessage(SampleData)

StampedSample = _reflection.GeneratedProtocolMessageType('StampedSample', (_message.Message,), dict(
  DESCRIPTOR = _STAMPEDSAMPLE,
  __module__ = 'Sample_pb2'
  # @@protoc_insertion_point(class_scope:akproto1.StampedSample)
  ))
_sym_db.RegisterMessage(StampedSample)


# @@protoc_insertion_point(module_scope)
