# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SparseSamples.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import proto.Sample_pb2 as Sample__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='SparseSamples.proto',
  package='akproto1',
  syntax='proto3',
  serialized_pb=_b('\n\x13SparseSamples.proto\x12\x08\x61kproto1\x1a\x0cSample.proto\"9\n\rSparseSamples\x12(\n\x07samples\x18\x01 \x03(\x0b\x32\x17.akproto1.StampedSampleb\x06proto3')
  ,
  dependencies=[Sample__pb2.DESCRIPTOR,])




_SPARSESAMPLES = _descriptor.Descriptor(
  name='SparseSamples',
  full_name='akproto1.SparseSamples',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='samples', full_name='akproto1.SparseSamples.samples', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=104,
)

_SPARSESAMPLES.fields_by_name['samples'].message_type = Sample__pb2._STAMPEDSAMPLE
DESCRIPTOR.message_types_by_name['SparseSamples'] = _SPARSESAMPLES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SparseSamples = _reflection.GeneratedProtocolMessageType('SparseSamples', (_message.Message,), dict(
  DESCRIPTOR = _SPARSESAMPLES,
  __module__ = 'SparseSamples_pb2'
  # @@protoc_insertion_point(class_scope:akproto1.SparseSamples)
  ))
_sym_db.RegisterMessage(SparseSamples)


# @@protoc_insertion_point(module_scope)
